@extends('layouts.app')
@section('title','Ask once. Stop chasing.')
@section('content')
<section class="landing-hero"><h1>Ask once.<br>Stop chasing.</h1><div class="landing-intro"><p>All the files, answers, and links you need from a client. One request. One simple link.</p><div class="landing-actions"><a class="button" href="{{ route('register') }}">Start your first request</a><a href="{{ route('demo') }}">See a demo</a></div><p class="field-help">Free during beta. Your clients don’t need an account.</p></div></section>
<section class="landing-workflow"><div><h2>A little less following up.</h2><p>Create a checklist, share the link, and let AskOnce remind your client about what’s still missing.</p><p>Files, short answers, longer text, links, and confirmations. Nothing extra to learn.</p></div><div class="example-request"><h2>Restaurant website content</h2><p class="field-help">An example of what you can collect.</p><div class="example-row"><span>Company logo</span><span>Received</span></div><div class="example-row"><span>Menu PDF</span><span>Still needed</span></div><div class="example-row"><span>About the restaurant</span><span>Still needed</span></div><p>Reminders include the missing items. Once everything required is in, they stop.</p></div></section>
<section class="landing-details"><h2>Easy to send. Easy to finish.</h2><dl><div><dt>No client login</dt><dd>Clients open their secure link, save each answer, and come back when they’re ready.</dd></div><div><dt>Private files</dt><dd>Uploaded files stay private. Only your business account can download them.</dd></div><div><dt>Thoughtful reminders</dt><dd>Morning emails in your timezone. Pause them any time; clients can stop them too.</dd></div></dl></section>
<section class="landing-pricing" id="pricing"><h2>Pricing</h2><div><p class="landing-price">Free while in beta.</p><p>Includes automatic reminders, 100 MB of file storage, {{ config('app.limits.clients') }} clients and {{ config('app.limits.open_requests') }} open requests. No card needed.</p><p>Paid plans come later. Beta accounts get notice before anything changes, and your data stays yours.</p></div></section>
<section class="landing-close"><h2>Get back to the work<br>you’re waiting to do.</h2><p>Create a request, share the link, and let the reminders do the chasing.</p><a class="button" href="{{ route('register') }}">Create your free account</a></section>
@endsection
